builds:
  - id: goobar
    binary: goobar
    main: ./cmd/goobar
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: goobar
    builds:
      - goobar
    format: zip
    name_template: 'goobar_{{ .Version }}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}'
